all3dp/printing-engine-client

src/app/action/navigation.js
test/unit/app/action/navigation.spec.js

Renew user id after successful order.

---

src/app/action/material.js
src/app/action/price.js
test/integration/app/action/model.spec.js
test/integration/app/action/price.spec.js
test/unit/app/action/price.spec.js

Fetch less prices

---

src/app/action/material.js
src/app/action/price.js
test/integration/app/action/model.spec.js
test/integration/app/action/price.spec.js
test/unit/app/action/price.spec.js

Reverts all3dp/printing-engine-client#324

Revert "Fetch less prices"

---

src/app/action/configuration.js
src/app/action/model.js
src/app/action/price.js
src/app/container/configuration-page.js
src/app/container/model-page.js
src/app/container/provider-section.js
src/app/container/upload-section.js
src/app/container/util/feature.js
src/app/lib/selector.js
test/integration/app/action/model.spec.js
test/unit/app/action/configuration.spec.js
test/unit/app/action/model.spec.js
test/unit/app/action/price.spec.js
test/unit/app/lib/selector.spec.js

This PR replaces the old one from #328
It refactors the feature toggles integration and adds all the requested tests as discussed [here](https://github.com/all3dp/printing-engine-client/pull/328#discussion_r144249820)
##	Testability

Refactor feature toggles

---

package-lock.json
package.json
test/setup.js

Add source map support

---

src/app/index.html

Add mobile support using fixed content width

---

config/default.js

Reduce polling rate

---

package-lock.json
package.json
src/app/index.js

Warn outdated browsers

---

src/app/action-type.js
src/app/action/order.js
src/app/container/success-page.js
src/app/reducer/order.js
src/app/type.js
test/unit/app/action/order.spec.js
test/unit/app/reducer/order.spec.js

Switch to order number and fix error handling for order-failed

---

src/app/container/cart-page.js

Fix us state name not displayed for billing address in order summary

---

src/app/component/upload-area.js
src/app/container/upload-section.js
src/sass/component/_upload-area.scss
stories/component/upload-area.js

Support multiple file formats

---

src/app/lib/formatter.js
src/app/type.js
stories/component/model-item.js
test/unit/app/lib/formatter.spec.js

Make dimensions optional

---

webpack.config.js

Fix webpack public path issue

---

src/app/index.js

Warn update browsers, fixes #347

---

src/app/action/material.js
src/app/action/price.js
src/app/component/select-menu-material-item.js
src/sass/component/_select-menu-material-item.scss
stories/component/select-menu-material-item.js
test/integration/app/action/material.spec.js
test/integration/app/action/model.spec.js
test/integration/app/action/price.spec.js
test/unit/app/action/material.spec.js
test/unit/app/action/price.spec.js

~~**This PR requires changes from the backend, do not merge yet**~~
**This PR is ready to be reviewed**
Re-adds the original PR from https://github.com/all3dp/printing-engine-client/pull/324 by reverting the revert from all3dp/printing-engine-client#332
😁

Re-add "Fetch less prices""

---

.nycrc
src/app/action/navigation.js
src/app/action/order.js
src/app/container/cart-page.js
src/app/type.js
test/unit/app/action/navigation.spec.js

Use this query parameters:
http://localhost:3000/?feature:invoice&invoice_key=geheimeschnitzelparty

Add invoice payment

---

src/app/container/direct-configuration-page.js
src/app/container/material-section.js

Add material information to shipping info tooltip

---

README.md
package.json
src/app/component/number-field.js

Fix value type issue of the number field, fixes #396

---

src/app/container/configuration-page.js

Fix user-id missing bug

---

src/app/container/app-layout.js

Add contact us link

---

src/app/lib/formatter.js
src/app/type.js
test/unit/app/lib/formatter.spec.js

Das Backend verwendet keinen `displayName` mehr
##	Testability

Remove shipping.displayName

---

config/default.js
src/app/action-type.js
src/app/action/price.js
src/app/component/payment-section.js
src/app/container/cart-page.js
src/app/container/modal/index.js
src/app/container/modal/price-location-changed.js
src/app/lib/offer.js
src/app/lib/poll.js
src/app/type.js
src/sass/component/_payment-section.scss
stories/component/payment-section.js
test/integration/app/action/material.spec.js
test/integration/app/action/model.spec.js
test/unit/app/action/price.spec.js
test/unit/app/lib/offer.spec.js
test/unit/app/lib/poll.spec.js

Fixes all3dp/printing-engine#255
##	Testability

Fix bug shipping address

---

config/production.js

Use /v2 routes for printing client production

---

src/app/action-next/init.js
src/app/action-next/modal.js
src/app/reducer-next/core.js
src/app/reducer-next/modal.js
src/app/selector/modal.js
src/app/type-next.js
test/integration/app/action-next/core.spec.js
test/integration/app/action-next/init.spec.js
test/integration/app/action-next/modal.spec.js

This PR is a follow up of #424. It finishes the refactoring of the init, modal and core tests.

Finish refactor tests

---

src/app/service/country.js

Add canada states

---

src/app/action/configuration.js
src/app/action/material.js
src/app/action/price.js
src/app/lib/selector.js
src/app/type.js
test/unit/app/action/configuration.spec.js
test/unit/app/lib/selector.spec.js

Fixes all3dp/printing-engine#397

Fix share config url

---

config/default.js
test/unit/app/lib/formatter.spec.js

Closes https://github.com/all3dp/printing-engine/issues/136

Add CAD and AUD currencies

---

src/app/component/payment-section.js
src/app/container/cart-page.js
src/sass/component/_payment-section.scss
stories/component/payment-section.js

https://github.com/all3dp/printing-engine-client/issues/492

Add links and terms to checkout box, fixes #492

---

config/default.js
src/app/service/stripe.js

Rename stripe text constants, fixes #490

---

src/app/container/cart-page.js
src/app/reducer/order.js
test/unit/app/reducer/order.spec.js

Fixes https://github.com/all3dp/printing-engine-client/issues/404

Fix disabled state of the payment buttons, fixes #404

---

src/app/action/user.js
src/app/index.js
src/app/service/printing-engine.js
test/integration/app/action/init.spec.js
test/unit/app/action/user.spec.js

Fix new state issues

---

bin/purge-cloudflare-cache.sh

Update files to purge from cloudflare cache

---

src/app/component/nav-bar.js
src/app/container/model-page.js

Replace slogan of Printing Service

---

src/app/component/payment-section.js
src/app/service/intercom.js

Patch for PR feedback https://github.com/all3dp/printing-engine-client/pull/511

Increase robustness of intercom integration on checkout page

---

src/app/component/payment-section.js
src/app/service/intercom.js
stories/component/payment-section.js

Open Intercom widget in checkout page for customer support

---

src/app/container/app-layout.js
stories/component/app.js
stories/component/footer.js

Update Footer Copyright to 2018

---

src/app/component/payment-section.js

Add knowledge base link to payment-section

---

src/app/component/payment-section.js
src/app/container/cart-page.js
stories/component/payment-section.js

Move Intercom service invocation from payment-section into cart-page

---

src/app/container/model-page.js

Only render promotion section when no model is uploaded

---

src/app/container/modal/fetching-price.js
src/sass/component/_overlay.scss
stories/component/overlay.js

Add new overlays for the new design

---

src/app/container/material-section.js

Add not printable link

---

src/app/component/nav-bar.js
src/app/container/model-page.js

Fix slogan in nav-bar and on model-page

---

src/app/component/notification.js
src/sass/_config.scss
src/sass/component/_button.scss
src/sass/component/_notification.scss
stories/component/button.js
stories/component/notification.js

 Add notification component and minor button, closes #446

---

src/app/action-next/model.js
src/app/action-next/user.js
src/app/reducer-next/model.js
src/app/type-next.js

Introduce id types

---

src/app/component/nav-bar.js
src/sass/component/_nav-bar.scss

Change Slogan to match Advertising Text

---

src/app/component/provider-item.js
src/app/component/provider-list.js
src/app/container/provider-section.js
src/app/lib/formatter.js
src/sass/component/_provider-item.scss
src/sass/component/_provider-list.scss
stories/component/provider-list.js
test/unit/app/lib/formatter.spec.js

Please merge PR #552 first!!
This is blocked by https://github.com/all3dp/material-structure/issues/32. After the information is present in the material structure this can be tested an merged.

Add production time to provider table, fixes #553

---

package-lock.json
package.json
src/app/lib/formatter.js
test/unit/app/lib/formatter.spec.js

Fix production time with undefined data

---

src/app/store.js

Always use the redux dev tools

---

src/app/component/info.js
src/app/component/provider-item.js
src/app/component/provider-list.js
src/sass/component/_provider-item.scss

Reshuffle provider table

---

src/app/container/finish-section.js
src/app/container/material-section.js

Move non printable materials to the end of the list

---

src/app/component/model-viewer.js
src/sass/component/_model-viewer.scss
stories/component/model-viewer.js

Part of #425 
Adds the model-viewer component without integrating it into the current application.

Add model-viewer component

---

src/app/action/user.js
test/unit/app/action/user.spec.js

Close openFetchingPriceModal before goToCart

---

src/app/container/modal/price-changed.js
src/app/container/modal/price-location-changed.js

Fix other modal close

---

src/app/type-next.js

Update types for the material structure

---

src/app/lib/printing-engine.js

Add price request v3 mock

---

src/app/action-next/index.js
src/app/action-next/modal.js
src/app/action-next/model-viewer.js
src/app/component/model-item.js
src/app/container/app-layout.js
src/app/container/modal-next/index.js
src/app/container/modal-next/model-viewer.js
src/app/container/upload-section.js
src/app/lib/error.js
src/app/lib/model.js
src/app/reducer-next/model-viewer.js
src/app/reducer-next/polling.js
src/app/reducer/index.js
src/app/selector/model-viewer.js
src/app/service/http-next.js
src/app/type-next.js
src/sass/_config.scss
src/sass/component/_model-item-error.scss
src/sass/component/_model-item-load.scss
src/sass/component/_model-item.scss
src/sass/component/_model-quantity-item.scss
src/sass/component/_model-viewer.scss
stories/component/model-item.js
test/.eslintrc
test/helper.js
test/integration/app/action-next/modal.spec.js
test/integration/app/action-next/model-viewer.spec.js
test/integration/app/action-next/polling.spec.js
test/setup.js
test/unit/app/lib/model.spec.js

Basiert auf https://github.com/all3dp/printing-engine-client/pull/596 und https://github.com/all3dp/printing-engine-client/pull/595. Erst mergen, wenn die zwei PRs gemerged wurden.
Closes https://github.com/all3dp/printing-engine-client/issues/425

Add model viewer

---

src/app/container/finish-section.js

Fixes https://github.com/all3dp/printing-engine-client/issues/590

Fix jumping material cards in finish-section

---

src/app/container/success-page.js

Add commission link

---

src/app/index.js
src/app/reducer-next/user.js
test/integration/app/action-next/user.spec.js

Remove create user on location detect

---

src/app/action-next/user.js
src/app/component/configuration-header.js
src/app/container-next/app-layout.js
src/app/container-next/cart-page.js
src/app/container-next/configuration-header-partial.js
src/app/container-next/footer-partial.js
src/app/container-next/material-page.js
src/app/container-next/model-list-partial.js
src/app/container-next/upload-page.js
src/app/lib/formatter.js
src/app/reducer-next/user.js
src/sass/component/_configuration-header.scss
stories/component/configuration-header.js
test/integration/app/action-next/init.spec.js
test/integration/app/action-next/user.spec.js

Update configuration header

---

src/app/container/finish-section.js

Fix issue when deleting models in the PC while fetching prices

---

src/app/container/success-page.js

Needed by https://github.com/all3dp/printing-engine/issues/620

Change referral programme text on success page

---

src/app/index.html

Replace Google Analytics with Google Tag Manager

---

src/app/action/model.js
src/app/reducer-next/model.js
test/integration/app/action/model.spec.js
test/unit/app/action/model.spec.js

Trigger Intercom upon model upload

---

src/app/action/model.js
src/app/reducer-next/model.js
test/integration/app/action/model.spec.js
test/unit/app/action/model.spec.js

Reverts all3dp/printing-engine-client#656

Revert "Trigger Intercom upon model upload"

---

src/app/lib/geolocation.js
src/app/service/country.js
test/unit/app/lib/geolocation.spec.js

Fixes https://github.com/all3dp/printing-engine/issues/459

Add British counties to list of country states

---

src/app/container/success-page.js

Remove referral programme teaser

---

src/app/action-next/cart.js
src/app/action-next/index.js
src/app/action-next/model.js
src/app/container-next/cart-page.js
src/app/container-next/material-page.js
src/app/container-next/model-list-partial.js
src/app/container-next/upload-page.js
src/app/lib/model.js
src/app/lib/selector/model.js
src/app/reducer-next/core.js
test/unit/app/lib/model.spec.js
test/unit/app/lib/selector/model.spec.js

Integrate add to cart action

---

src/app/component/overlay-header-bar.js
src/app/component/static-field.js
src/app/container-next/address-page.js
src/app/container-next/checkout-layout.js
src/app/container-next/util/form.js
src/app/container-next/util/guard.js
src/app/router.js
src/sass/component/_icon-link.scss
src/sass/component/_overlay-header-bar.scss
src/sass/component/_process-step.scss
src/sass/component/_static-field.scss
stories/component/icon-link.js
stories/component/overlay-header-bar.js
stories/component/static-field.js

https://github.com/all3dp/printing-engine-client/issues/646

Update Address page to match new Design

---

src/app/container-next/success-page.js
src/app/router.js
src/sass/component/_provider-teaser.scss
stories/component/provider-teaser.js

Add success page

---

src/app/action-next/navigation.js
src/app/container-next/address-page.js
src/app/container-next/app-layout.js
src/app/container-next/material-page.js
src/app/container-next/upload-page.js
src/app/index.js
src/app/type-next.js

Show warning on upload page after location change

---

src/app/component/model-item.js
src/app/container-next/cart-page.js
src/app/container-next/review-order-page.js
src/app/lib/selector/model.js
src/app/reducer-next/core.js
stories/component/model-item.js
test/unit/app/lib/selector/model.spec.js

 Bind review-oder page to state

---

src/app/reducer-next/core.js

Rethrow fatal erros

---

src/app/container-next/material-page.js

Format price for no additional shipping costs in provider table

---

src/app/component/upload-area.js

https://github.com/all3dp/printing-engine-client/issues/728

Fix upload area to not call on change with an empty files array

---

src/app/component/payment-section.js

Fix checkout label

---

src/app/reducer-next/core.js

Automatically select all models in the list after the upload

---

src/app/container-next/upload-page.js
src/sass/_config.scss
src/sass/component/_upload-area.scss
stories/component/upload-area.js

Use bigger upload field if no files have been uploaded

---

src/app/container-next/checkout-layout.js

https://github.com/all3dp/printing-engine-client/issues/722

Fix intercom on all checkout layout pages

---

src/app/container/cart-page.js
src/app/container/review-order-page.js
src/app/lib/selector.js

Update material names in 'your order'

---

src/sass/component/_model-item.scss
src/sass/component/_upload-model-item.scss

Always show buttons in ModelItem and UploadModelItem

---

.travis.yml
config/production.js

Deploy multi-model-upload client to stage

---

.travis.yml

Use AWS access for staging env

---

src/app/container/cart-page.js
src/app/container/model-list-partial.js
src/app/container/upload-page.js

Remove `…` for the choose material label

---

.travis.yml
config/production.js

Make `master` branch deploy to `printing-engine-prod` again ;)

Revert deploy to stage

---

src/app/component/provider-item/provider-item.js
src/app/container/material-page.js
stories/component/provider-list.js

Skip cart page if no item is on upload page

---

src/app/container/address-page.js

Update the phone number to be required

---

config/default.js

Update sentry client key

---

src/app/action/modal.js
src/app/component/location-field/location-field.js
src/app/container/address-page.js
src/app/container/modal/confirm-location-change.js
src/app/container/modal/index.js
src/app/container/modal/pick-location.js
src/app/reducer/core.js

Fix pick location issue

---

src/app/component/annotated-table-cell/_annotated-table-cell.scss
src/app/component/provider-item/provider-item.js
stories/component/annotated-table-cell.js

Update provider item

---

src/app/component/annotated-table-cell/_annotated-table-cell.scss
src/app/component/provider-item/_provider-item.scss
src/app/component/provider-item/provider-item.js
src/app/component/provider-list/provider-list.js
src/app/container/material-partial.js
src/sass/_config.scss

Highlight cheapest provider

---

src/app/container/configuration-header-partial.js
stories/component/app.js
stories/component/configuration-header.js

Remove shipping label from configuration header

---

src/app/component/annotated-table-cell/_annotated-table-cell.scss
src/app/component/provider-item/_provider-item.scss
src/app/component/provider-item/provider-item.js

Make cheapest provider price bold only

---

src/app/action/navigation.js
src/app/container/configuration-page.js

Fix routing issue for preconfigured models

---

src/app/container/material-partial.js

Fix load with config location issue

---

config/default.js
src/app/container/address-page.js
src/app/reducer/core.js
src/app/service/local-storage.js
src/app/type.js

Save address to local storage

---

src/app/component/logo/logo.js

Change logo service name

---

config/default.js
src/app/container/address-page.js
src/app/reducer/core.js

Fix bugs related to address and location issues

---

src/app/container/modal/pick-unit.js
src/app/container/review-order-page.js

Minor update of labels

---

src/app/component/provider-box-section/provider-box-section.story.js
src/app/component/provider-box/provider-box.story.js
src/app/component/provider-list/provider-list.story.js
src/app/container/material-partial.js

Add material name and color to provider item description

---

src/app/action/modal.js
src/app/container/modal/error.js
src/app/container/modal/index.js
src/app/container/review-order-page.js
src/app/lib/error.js
src/app/lib/error.spec.js
src/app/service/stripe.js
src/app/type.js

Show dismissible error dialog when payment fails

---

.prettierrc
src/app/component/button/_button.scss
src/app/component/provider-list/_provider-list.scss
src/app/component/provider-list/provider-list.js
src/app/component/provider-list/provider-list.story.js
src/app/container/material-partial.js

Hide provider list

---

.travis.yml
package.json
src/app/action/core.js
src/app/action/model.js
src/app/container/modal/pick-unit.js
src/app/reducer/core.js

Add use same material question

---

src/app/container/address-page.js

Make VAT ID optional on address page

---

src/app/container/address-page.js

Fix stateCode field validation

---

src/app/container/modal/pick-unit.js
src/app/container/upload-page.js
src/app/reducer/core.js

Change scroll behaviour

---

src/app/container/review-order-page.js
src/app/service/logging.js

Add error logging to the payment process

---

src/app/action/model.js
src/app/lib/printing-engine.js
src/app/reducer/core.js

Diese PR funktioniert nur zusammen mit https://github.com/all3dp/printing-engine/pull/915
@webholics den PR bitte nur approven @henry-all3dp muss den mergen

Add feature to deal with multi file response for one uploaded file

---

src/app/component/upload-area/upload-area.story.js
src/app/container/upload-page.js

Change upload area description

---

src/app/lib/printing-engine.ts
src/app/reducer/model-viewer.ts

Fix model viewer error

---

src/app/container/upload-page.js

Add permanent warning on upload page regarding christmas shipping

---

src/app/container/upload-page.js

This reverts commit 3680e6889419f45f5c5977c659cbe02628cc32e5.

Revert "Add permanent warning on upload page regarding christmas shipping"

---

src/app/index.js

Fix ie11 bug for removing the spashscreen

---

src/app/component/loading-checkmark/_loading-checkmark.scss
src/app/component/loading-checkmark/loading-checkmark.story.js
src/app/container/material-partial.js

Hide loading checkmark with 30 delay

---

src/app/component/select-field/_select-field.scss
src/app/component/select-field/select-field.story.js

Add error modifier to select-field

---

src/app/component/price/_price.scss
src/app/component/price/price.js

Change size of the loading checkmark

---

.travis.yml

Reverts all3dp/printing-engine-client#922

Revert "Remove sudo:false from travis config"

---

src/app/component/app/app.story.js
src/app/component/footer/footer.story.js
src/app/component/provider-box/_provider-box.scss
src/app/component/provider-box/provider-box.js
src/app/component/provider-box/provider-box.story.js
src/app/component/provider-item/provider-item.js
src/app/component/provider-list/_provider-list.scss
src/app/component/provider-list/provider-list.js
src/app/container/footer-partial.js
src/app/container/material-partial.js

Add detailed information to delivery time

---

package-lock.json
package.json

Update webpack-dev-server dependency

---

src/app/component/material-card/material-card.js
src/app/container/material-partial.js
src/app/container/upload-page.js

Remove zverse integration

---

src/app/container/modal/address-form.js

Prevent errors from legacy address data

---

src/app/component/overlay/overlay.js
src/app/component/overlay/overlay.story.js
src/app/container/modal/address-form.js

https://github.com/all3dp/printing-engine-client/issues/959

Don't close address modal on click outside

---

src/app/action/modal.ts
src/app/component/overlay/_overlay.scss
src/app/container/location-info-partial.js
src/app/container/modal/address-form.js
src/app/container/modal/pick-location.js
src/app/container/upload-page.js
src/app/reducer/core.ts

Add location-info-partial

---

src/app/component/upload-layout/_upload-layout.scss
src/app/component/upload-layout/index.js
src/app/component/upload-layout/upload-layout.js
src/app/component/upload-layout/upload-layout.story.js

Add upload layout component

---

src/app/index.html

Increase the splash logo size

---

src/app/component/location-field/_location-field.scss
src/app/component/location-field/location-field.js

Only allow valid values in the location field

---

src/app/component/overlay/overlay.js
src/app/container/modal/address-form.js

 Fix scrolling in address form

---

.travis.yml

Change to stage based deployment

---

src/app/component/input-field/input-field.js
src/app/component/number-field/number-field.js

Prevent autocomplete on all text inputs

---

src/app/component/input-field/input-field.js
src/app/component/number-field/number-field.js

Reenable autocomplete

---

src/asset/robots.txt
webpack.config.js

Add robots.txt to dist build

---

src/app/container/upload-page.js

https://github.com/all3dp/printing-engine-client/issues/989

Change upload page button text

---

src/app/component/provider-box/provider-box.js
src/app/container/material-partial.js

https://github.com/all3dp/printing-engine-client/issues/990

Remove onClick on ProviderBox

---

src/app/component/upload-model-item/_upload-model-item.scss
src/app/component/upload-model-item/upload-model-item.js
src/app/component/upload-model-item/upload-model-item.story.js

https://github.com/all3dp/printing-engine-client/issues/991

Make Image clickable for select and deselect on UploadModelItem

---

src/app/component/model-item/model-item.js
src/app/container/cart-page.js
src/app/container/review-order-page.js
src/app/lib/selector.spec.js
src/app/lib/selector.ts

Add production time to model item delivery indication

---

src/app/action/core.ts
src/app/container/review-order-page.js
src/app/reducer/core.ts
src/app/type.ts

Fix app reset and restore the user if possible

---

src/app/index.html

Change title tag to craftcloud

---

package-lock.json
package.json

Update sentry cli module

---

src/app/index.html

Add proof pixel

---

src/app/index.html

Closes #1034 
Reverts all3dp/printing-engine-client#1030

Revert "Add proof pixel"

---

src/app/index.html

Closes #1034 
Reverts all3dp/printing-engine-client#1017

Revert "Integrate use-proof service"

---

src/app/index.html

Update Google Tag Manager script

---

src/app/index.html

Remove mixpanel

---

bin/purge-cloudflare-cache.sh

Change cloudflare purge script to support new cloudflare cache mechanism

---

src/app/container/upload-page.js

Reformat upload page contact us text

---

package-lock.json
package.json
src/app/index.js

This should fix: https://sentry.io/organizations/all3dp-gmbh/issues/970203339/events/eabd0830c2fd428b8c247217c925fae6/

Update browser update

---

src/app/container/cart-page.js
src/app/container/material-partial.js
src/app/container/review-order-page.js

- Fix images on cloudinary
- Updated cloudinary image size to the correct one.

Fix cloudinary images

---

src/app/component/progress/_progress.scss
src/app/component/upload-model-item-error/_upload-model-item-error.scss
src/app/component/upload-model-item-load/_upload-model-item-load.scss
src/app/component/upload-model-item/_upload-model-item.scss
src/sass/_config.scss

Fix progress bar

---

src/app/component/nav-bar/nav-bar.story.js
src/app/container/material-page.js
src/app/container/nav-bar-partial.js
src/app/container/order-status-page.js
src/app/container/review-order-page.js
src/app/index.html

Update nav bar and remove intercom bubble

---

config/default.ts
src/app/container/nav-bar-partial.js
src/app/service/intercom.ts

Use contact email as intercom fallback

---

src/app/component/color-card/_color-card.scss
src/app/component/material-slider/_material-slider.scss
src/sass/_config.scss

Update color card width

---

src/app/action/core.ts
src/app/component/container/_container.scss
src/app/component/container/container.js
src/app/component/container/container.story.js
src/app/component/model-upload-list/_model-upload-list.scss
src/app/component/model-upload-list/model-upload-list.js
src/app/component/model-upload-list/model-upload-list.story.js
src/app/component/upload-area/_upload-area.scss
src/app/container/modal/pick-unit.js
src/app/container/upload-page.js
src/app/reducer/core.ts
test/cypress/integration/simple.spec.js

- Go to material page if user just uploads one single model
- Get rid of the "use same material" radio button in the upload modal
- Minor layout changes in the upload page

Optimize look & feel of upload page

---

src/app/component/cart-model-item/_cart-model-item.scss

Make right content larger in CartModelItem

---

src/app/component/upload-area/_upload-area.scss
src/app/component/upload-area/upload-area.story.js
src/app/container/modal/address-form.js
src/app/container/modal/confirm-currency-change.js
src/app/container/modal/confirm-location-change.js
src/app/container/upload-page.js

Decrease upload area size and rename choose material

---

src/app/container/cart-page.js
src/app/container/modal/address-form.js

Fix state name in address form

---

src/app/container/material-partial.js

Fix reloading offers in material partial

---

config/default.ts
src/app/component/app-layout/app-layout.story.js
src/app/container/nav-bar-partial.js
src/app/container/upload-page.js
src/asset/icon/intercom.svg

Update intercom help button in nav bar

---

src/app/component/button/_button.scss
src/app/component/page-layout/_page-layout.scss
src/app/component/page-layout/page-layout.js
src/app/component/page-layout/page-layout.story.js
src/app/component/sticky-footer/_sticky-footer.scss
src/app/container/order-status-page.js
src/app/container/upload-page.js
src/sass/_config.scss

Make stickyFooter sticky inside content

---

src/app/container/material-page.js

Keep selection when switching between upload and material page

---

src/app/component/recommended-offer-section/_recommended-offer-section.scss
src/sass/_config.scss

Adapt xlarge breakpoint to optimize material page

---

src/app/container/material-page.js

Fix model selection on material page

---

src/app/container/material-page.js
src/app/container/upload-page.js

Fix bugs regarding uploading and upload errors

---

src/app/container/edit-material-page.js
src/app/container/material-partial.js

Clear model selection when adding models to cart

---

src/app/container/cart-page.js
src/sass/util/_spacing.scss

Quick fix spacing with tooltip on cart page

---

src/app/component/config-model-list/_config-model-list.scss

Slow down 2nd phase of add to cart animation

---

src/app/component/page-layout/page-layout.story.js
src/app/container/material-partial.js
src/app/container/modal/address-form.js
src/app/container/modal/confirm-currency-change.js
src/app/container/modal/confirm-location-change.js
src/app/container/upload-page.js

Change wording on upload page

---

src/app/container/configuration-page.js
src/app/reducer/core.ts

resolves https://github.com/all3dp/printing-engine-client/issues/1165

Fix default selection for configured models

---

src/app/container/material-page.js
src/app/container/upload-page.js
src/app/reducer/core.ts

Fix duplication bug

---

src/app/container/material-page.js
src/app/container/upload-page.js

resolves https://github.com/all3dp/printing-engine-client/issues/1161

Fix select all bug

---

src/app/component/material-slider/material-slider.js
src/app/component/tool-layout/_tool-layout.scss
src/app/service/animate.ts
src/app/service/scroll-to.ts

Fix smooth scrolling for older browsers

---

src/app/container/cart-page.js
src/app/container/modal/address-form.js
src/app/container/upload-page.js
test/cypress/integration/simple.spec.js

Update checkout button flow
and background of the upload page
Resolves https://github.com/all3dp/printing-engine-client/issues/1144

Update checkout button flow

---

src/app/index.js
src/app/service/intercom.ts

Open intercom on incoming messages

---

src/app/index.js
src/app/service/google-analytics.ts

resolves https://github.com/all3dp/printing-engine-client/issues/1195

Add page impression tracking

---

config/default.ts
src/app/container/modal/address-form.js
src/app/reducer/core.ts
src/app/service/local-storage.ts

resolves #1041, resolves #1042

Preload user from local storage

---

src/app/component/cart-model-item/_cart-model-item.scss
src/app/component/cart-model-item/cart-model-item.js
src/app/component/cart-model-item/cart-model-item.story.js
src/app/component/upload-model-item/_upload-model-item.scss
src/app/component/upload-model-item/upload-model-item.js
src/app/component/upload-model-item/upload-model-item.story.js
src/app/container/cart-page.js
src/app/container/edit-material-page.js
src/app/container/material-page.js
src/app/container/upload-page.js

Open model preview on preview image click

---

src/app/service/local-storage.ts

resolves https://github.com/all3dp/printing-engine-client/issues/1206
fixed this sentry issue: https://sentry.io/organizations/all3dp-gmbh/issues/1098367813/?project=193367&query=is%3Aunresolved&statsPeriod=14d&utc=true

 Fix missing local storage issue

---

src/app/component/cart-flyout/_cart-flyout.scss
src/app/component/cart-flyout/cart-flyout.js
src/app/component/cart-nav-link/cart-nav-link.js
src/app/component/cart-nav-link/cart-nav-link.story.js

Fixes https://github.com/all3dp/printing-engine-client/issues/1193

Fix flyout positioning issue

---

src/app/service/local-storage.ts

Fix local storage issues

---

src/app/lib/printing-engine.ts

Fix StripePaymentResponse and InvoicePaymentResponse type definitions

---

src/app/component/checkbox-field/_checkbox-field.scss
src/app/component/checkbox-field/checkbox-field.js
src/app/component/checkbox-field/checkbox-field.story.js
src/app/component/country-select-field/_country-select-field.scss
src/app/component/country-select-field/country-select-field.js
src/app/component/country-select-field/country-select-field.story.js
src/app/component/country-select-field/index.js
src/app/component/input-field/_input-field.scss
src/app/component/input-field/input-field.js
src/app/component/input-field/input-field.story.js
src/app/component/labeled-checkbox/_labeled-checkbox.scss
src/app/component/labeled-checkbox/labeled-checkbox.js
src/app/component/labeled-checkbox/labeled-checkbox.story.js
src/app/component/select-field/_select-field.scss
src/app/component/select-field/select-field.js
src/app/component/select-field/select-field.story.js
src/app/container/cart-page.js
src/app/container/modal/address-form.js
src/app/container/util/form.js
src/app/lib/validator.spec.js
src/app/lib/validator.ts
src/sass/_config.scss

resolves https://github.com/all3dp/printing-engine-client/issues/1131

Update address form

---

bin/get-sentry-release-version.sh

Add missing sentry release version

---

src/app/container/cart-page.js

Note: this changes should go live immediately.
Changes have been validated by @Dansken

Update contact texts on cart page

---

src/app/container/cart-page.js
src/app/service/local-storage.ts

merge master back to dev

---

package-lock.json
package.json
src/app/action/configuration.ts
src/app/action/model.ts
src/app/action/polling.ts
src/app/action/timeout.ts
src/app/component/input-field/input-field.js
src/app/component/labeled-checkbox/labeled-checkbox.js
src/app/component/upload-area/upload-area.js

It should fix both: #1237 and #1238

Replace uniqueId with true uuid to fix issue with session store

---

package-lock.json
package.json
src/app/action/configuration.ts
src/app/action/model.ts
src/app/action/polling.ts
src/app/action/timeout.ts
src/app/component/input-field/input-field.js
src/app/component/labeled-checkbox/labeled-checkbox.js
src/app/component/upload-area/upload-area.js
src/app/container/cart-page.js

merge hotfix on master back to develop

---

src/app/index.html
src/sass/_config.scss

Update breakpoints and update viewport

---

src/app/component/column/_column.scss
src/app/component/configuration-header/_configuration-header.scss
src/app/component/footer/_footer.scss
src/app/component/form-row/_form-row.scss
src/app/component/logo/_logo.scss
src/app/component/notification/_notification.scss
src/app/component/order-confirmation-item/_order-confirmation-item.scss
src/app/component/order-confirmation-list/_order-confirmation-list.scss
src/app/component/provider-teaser/_provider-teaser.scss
src/app/component/recommended-offer-section/_recommended-offer-section.scss
src/app/container/material-partial.js
src/sass/mediaqueries.json
src/sass/util/_responsive.scss

Refactor breakpoint names

---

src/app/component/cart-nav-link/_cart-nav-link.scss
src/app/component/cart-nav-link/cart-nav-link.js
src/app/component/logo/_logo.scss
src/app/component/nav-bar/_nav-bar.scss
src/app/component/nav-bar/nav-bar.story.js
src/app/component/nav-link/_nav-link.scss
src/app/container/nav-bar-partial.js
src/sass/_config.scss

Make nav-bar and its contents responsive

---

src/app/component/input-field/input-field.js
src/app/component/labeled-checkbox/labeled-checkbox.js
src/app/component/radio-button-group/radio-button-group.js
src/app/component/radio-button/radio-button.js
src/app/component/upload-area/upload-area.js

Fix generated ids in fields

---

src/app/component/order-confirmation-list/_order-confirmation-list.scss
src/app/container/success-page.js

Optimize success page for mobile

---

src/app/index.html

Optimize bootsplash logo for mobile

---

src/app/reducer/core.ts

Fix shippings in shared cart scenario

---

src/app/container/cart-page.js
src/app/container/offer-footer-partial.js

Fix wording of share cart button and shipping tooltip

---

src/app/container/offer-footer-partial.js

Fix typo in tooltip

---

src/app/lib/model.spec.js
src/app/lib/model.ts
src/app/reducer/core.ts

Fix creating new cart during quantity changes

---

webpack.config.js

Include js and css build files via hash to bust caches

---

src/app/component/description-list/_description-list.scss
src/app/component/material-slider/_material-slider.scss
src/app/component/material-slider/material-slider.js
src/app/component/material-step-section/_material-step-section.scss
src/app/component/offer-card/_offer-card.scss
src/app/component/offer-item/_offer-item.scss
src/app/component/offer-list/_offer-list.scss
src/app/component/positioning-portal/positioning-portal.js
src/app/component/radio-button/_radio-button.scss
src/app/container/material-partial.js

Optimize material page content for mobile

---

src/app/action/navigation.ts
src/app/component/notification/_notification.scss
src/app/container/cart-offer-page.js
src/app/container/upload-page.js
src/app/lib/selector.spec.js
src/app/lib/selector.ts
src/app/reducer/core.ts

Fallback to upload page if cart offer cannot be fully restored

---

src/app/service/country.ts

Add Italian state list

---

src/app/component/material-card/_material-card.scss
src/app/component/material-card/material-card.js
src/app/component/material-card/material-card.story.js
src/app/container/material-partial.js

resolves https://github.com/all3dp/printing-engine-client/issues/1282

Split production and shipping cost on the Material Card

---

cypress.json

Longer timeout for cypress

---

src/app/component/cart-model-item/_cart-model-item.scss
src/app/component/cart-model-item/cart-model-item.js

Add fulfilled by to the cart model item

---

src/app/container/material-page.js
src/app/container/material-partial.js
src/app/container/upload-page.js
src/app/lib/selector.spec.js
src/app/lib/selector.ts

Fix issue with missing modelConfigs on upload page

---

src/app/component/material-card/material-card.js
src/app/component/material-card/material-card.story.js
src/app/container/material-partial.js

Allow material card click on mobile

---

src/app/component/cart-model-item/cart-model-item.js
src/app/container/material-partial.js

Change fulfilled by to produced by

---

src/app/component/description-list/_description-list.scss
src/app/component/offer-item/_offer-item.scss
src/app/component/offer-list/_offer-list.scss
src/app/component/recommended-offer-section/_recommended-offer-section.scss
src/app/container/material-partial.js

https://github.com/all3dp/printing-engine-client/issues/1330
https://github.com/all3dp/printing-engine-client/issues/1331

Max width for offer list, fix breakpoints and offer card content

---

src/app/container/material-partial.js
src/app/container/offer-footer-partial.js

https://github.com/all3dp/printing-engine-client/issues/1332
https://github.com/all3dp/printing-engine-client/issues/1333

Show gross price and shipping separately in material card

---

src/app/container/cart-page.js

Fix duplicate address line 2 on cart page

---

src/app/component/offer-card/_offer-card.scss
src/app/container/cart-page.js
src/app/container/material-partial.js

Show gross prices on cart page

---

src/app/container/modal/pick-location.js

Fix race condition in pick location modal

---

src/app/container/material-partial.js

Align prices to the right

---

test/cypress/integration/session.spec.js
test/cypress/integration/share-cart.spec.js

Fix cypress tests

---

config/default.ts
src/app/lib/formatter.spec.js
src/app/lib/formatter.ts

https://github.com/all3dp/printing-engine-client/issues/1347

Always prepend the currency on prices

---

cypress.json
src/app/component/headline/_headline.scss
src/app/component/headline/headline.js
src/app/component/material-card/_material-card.scss
src/app/component/material-step-section/_material-step-section.scss
src/app/component/offer-list/_offer-list.scss
src/app/component/search-field/_search-field.scss
src/app/component/sticky-footer/_sticky-footer.scss
src/app/component/sticky-footer/sticky-footer.js
src/app/container/cart-page.js
src/app/container/modal/share-cart.js
src/app/container/upload-page.js
test/cypress/integration/share-cart.spec.js
test/cypress/integration/simple.spec.js

Minor styling adaptations and fixes

---

src/app/component/tool-layout/_tool-layout.scss
src/app/container/material-partial.js
test/cypress/integration/share-cart.spec.js

Fix vertical scrolling on material page on iOS

---

config/default.ts

Update manufacturer descriptions

---

src/app/container/material-partial.js

Fix Tooltip shown when fetching prices

---

src/app/component/provider-image/_provider-image.scss

Fix provider image

---

config/development.ts
src/app/lib/selector.spec.js
src/app/lib/selector.ts
test/cypress/integration/session.spec.js
test/cypress/integration/share-cart.spec.js
test/cypress/integration/simple.spec.js

Simplify cypress tests

---

src/app/action/cart.ts
src/app/container/cart-offer-page.js
src/app/lib/printing-engine.spec.js
src/app/lib/printing-engine.ts
src/app/reducer/core.ts

Fallback to configuration if loading cart offer fails

---

config/default.ts
package-lock.json
package.json
src/app/external.d.ts
src/app/service/logging.ts

resolves https://github.com/all3dp/printing-engine-client/issues/1315

Update sentry logger with latest version

---

src/app/container/material-partial.js

Sort finishGroup and color by price

---

src/app/component/offer-item/_offer-item.scss
src/app/container/material-partial.js

Update best prices box breakpoint behaviour

---

src/app/container/modal/error.js
src/app/container/modal/fatal-error.js
src/app/container/modal/pick-location.js

Optimize modals for mobile

---

src/app/action/core.ts
src/app/action/modal.ts
src/app/container/main-app.js
src/app/container/modal/index.js
src/app/container/modal/service-unavailable.js
src/app/reducer/core.ts
src/app/type.ts

Add Service currently unavailable feature

---

src/app/container/cart-page.js

Use prices without vat in the cart

---

src/app/component/provider-image/_provider-image.scss
src/app/component/provider-image/provider-image.js
src/app/component/provider-image/provider-image.story.js
src/app/container/cart-page.js
src/app/container/material-partial.js

Show provider image for the producer

---

src/app/container/material-partial.js

resolves https://github.com/all3dp/printing-engine-client/issues/1382

Fix firefox sorting problem

---

src/app/component/cart-model-item/_cart-model-item.scss

resolves #1396 
Screenshot after the fix

Fix edge bug in cart model item

---

src/app/lib/selector.spec.js
src/app/lib/selector.ts
src/app/type.ts

Remove printingServiceName from finish group

---

src/app/component/cart-model-item/cart-model-item.js
src/app/component/provider-image/_provider-image.scss
src/app/component/provider-image/provider-image.js
src/app/container/cart-page.js

Use minor ProductImage on cart page

---

src/app/container/cart-page.js
src/app/lib/printing-engine.ts

Update create order request according to api change

---

src/app/container/upload-page.js

resolves https://github.com/all3dp/printing-engine-client/issues/1393

Change labels on 100% upload progress

---

src/app/container/upload-page.js

See https://github.com/all3dp/printing-engine-client/pull/1419#issuecomment-540390762

Fix upload title

---

config/default.ts

Hotfix which should go live immediately 
resolves https://github.com/all3dp/printing-engine-client/issues/1424

Add missing vendor descriptions
